name: eco_mapa_3
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.5.0
  google_maps_flutter: ^2.9.0
  cloud_firestore: ^5.4.2
  firebase_auth: ^5.3.0
  geolocator: ^7.6.2
  geocoding: ^3.0.0
  image: ^4.2.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/beneficios/beneficios-del-reciclaje.jpg
    - assets/images/beneficios/grafico.png
    - assets/images/separacion_residuos/istockphoto-1092504754.jpg
    - assets/images/separacion_residuos/RECICLAJE.jpg
    - assets/images/separacion_residuos/recycle-bin.png
